package approvalworkflow.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Dimension;
import java.awt.BorderLayout;
import java.awt.Font;
import javax.swing.JLabel;
import java.awt.GridLayout;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import javax.swing.JButton;
import javax.swing.SwingUtilities;

public class MyWorkflowApp extends JFrame {


  private JPanel submitpanel = new JPanel();
  private JPanel approvalpanel = new JPanel();
  private ActionListener submitlistener = new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent p1) {
      createApproval();
    }
  };

  public MyWorkflowApp() {
    setTitle("MyWorkflowApp");
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    add(submitpanel);
    submitpanel.setPreferredSize(new Dimension(500, 500));
    panelcreator(submitpanel);
    pack();
    setVisible(true);
  }

  public void panelcreator(JPanel submitpanel) {

    submitpanel.setLayout(new BorderLayout());
    Font font = new Font("Serif", Font.BOLD, 20);
    JLabel titleLabel;
    titleLabel = new JLabel("New Request", JLabel.CENTER);
    titleLabel.setFont(new Font("Serif", Font.BOLD, 30));
    submitpanel.add(titleLabel, BorderLayout.PAGE_START);

    String[] userList = {"User 1", "User 2"};

    JPanel body;
    body = new JPanel(new GridLayout(4, 2));
    body.setPreferredSize(new Dimension(300, 300));
    JLabel requestlabel = new JLabel("Request", JLabel.CENTER);
    requestlabel.setFont(font);
    body.add(requestlabel);
    body.add(new JTextField("here goes the item name"));
    JLabel userlabel = new JLabel("User", JLabel.CENTER);
    userlabel.setFont(font);
    body.add(userlabel);
    JComboBox userListBox = new JComboBox();
    body.add(userListBox);
    JLabel categorylabel = new JLabel("Category", JLabel.CENTER);
    categorylabel.setFont(font);
    body.add(categorylabel);
    JComboBox categoryListBox = new JComboBox();
    body.add(categoryListBox);
    JLabel approveLabel = new JLabel("Must be approved by", JLabel.CENTER);
    approveLabel.setFont(font);
    body.add(approveLabel);
    JLabel approvedbyLabel = new JLabel("List of approvers goes here", JLabel.CENTER);
    approvedbyLabel.setFont(font);
    body.add(approvedbyLabel);
    submitpanel.add(body, BorderLayout.CENTER);

    JButton submitButton = new JButton("SUBMIT");
    submitButton.setPreferredSize(new Dimension(150, 100));
    submitButton.setFont(new Font("Serif", Font.BOLD, 30));
    submitButton.addActionListener(submitlistener);
    submitpanel.add(submitButton, BorderLayout.PAGE_END);

  }

  public void createApproval() {

    setTitle("Approval");
    setDefaultCloseOperation(EXIT_ON_CLOSE);
    remove(submitpanel);
    add(approvalpanel);
    approvalpanel.setPreferredSize(new Dimension(400, 400));
    approvalpanelcreator(approvalpanel);
    pack();
    setVisible(true);


  }

  public void approvalpanelcreator(JPanel approvalpanel) {

    approvalpanel.setLayout(new GridLayout(3, 1));
    Font font = new Font("Serif", Font.BOLD, 20);
    JLabel titlelabel = new JLabel("Request", JLabel.CENTER);
    titlelabel.setFont(font);
    approvalpanel.add(titlelabel);
    JLabel itemlabel = new JLabel("Item name goes here", JLabel.CENTER);
    itemlabel.setFont(font);
    approvalpanel.add(itemlabel);
    JLabel acceptlabel = new JLabel("Accepted By", JLabel.CENTER);
    acceptlabel.setFont(font);
    approvalpanel.add(acceptlabel);
    JLabel declinelabel = new JLabel("Declined By", JLabel.CENTER);
    declinelabel.setFont(font);
    approvalpanel.add(declinelabel);
    JLabel acceptedbylabel = new JLabel("Users who accepted", JLabel.CENTER);
    acceptedbylabel.setFont(font);
    approvalpanel.add(acceptedbylabel);
    JLabel declinedbylabel = new JLabel("Users who declined", JLabel.CENTER);
    declinedbylabel.setFont(font);
    approvalpanel.add(declinedbylabel);
  }

  public static void main(String[] args) {
    SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        new MyWorkflowApp();
      }
    });
  }
}
