package approvalworkflow.sandbox;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class TypeList {
  private SNode types;
  public enum types {
    int(),
    boolean(),
    double(),
    string()
  }
}
