package approvalworkflow.sandbox;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class UserList {
  private List<User> users;
  public UserList() {
    ListSequence.fromList(users).addElement(new User("Kolos", 2, null));
    ListSequence.fromList(users).addElement(new User("Sanyi", 1, null));
    ListSequence.fromList(users).addElement(new User("Gergő", 2, null));
  }
}
