package approvalworkflow.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Approval = 0;
  public static final int Attribute = 1;
  public static final int AttributeList = 2;
  public static final int AttributeReference = 3;
  public static final int AttributeWithValue = 4;
  public static final int Category = 5;
  public static final int CategoryList = 6;
  public static final int CategoryReference = 7;
  public static final int Requirement = 8;
  public static final int Rule = 9;
  public static final int RuleList = 10;
  public static final int RuleReference = 11;
  public static final int User = 12;
  public static final int UserList = 13;
  public static final int UserReference = 14;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L);
    builder.put(0x16f8cd7a6186e86fL, Approval);
    builder.put(0x16f8cd7a6186e877L, Attribute);
    builder.put(0x2b7b4a5722feffbdL, AttributeList);
    builder.put(0x49291be038e1f869L, AttributeReference);
    builder.put(0x51d1adf751ca427aL, AttributeWithValue);
    builder.put(0x16f8cd7a6186e86dL, Category);
    builder.put(0x2b7b4a5722fc7236L, CategoryList);
    builder.put(0x49291be038e1f854L, CategoryReference);
    builder.put(0x16f8cd7a6186e862L, Requirement);
    builder.put(0x16f8cd7a6186e86eL, Rule);
    builder.put(0x2b7b4a5722feff6aL, RuleList);
    builder.put(0x49291be038e1f87bL, RuleReference);
    builder.put(0x16f8cd7a61858813L, User);
    builder.put(0x49291be038e4df83L, UserList);
    builder.put(0x49291be038e1f83dL, UserReference);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
