package approvalworkflow.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Approval = 0;
  public static final int Attribute = 1;
  public static final int Category = 2;
  public static final int Requirment = 3;
  public static final int Rule = 4;
  public static final int User = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L);
    builder.put(0x16f8cd7a6186e86fL, Approval);
    builder.put(0x16f8cd7a6186e877L, Attribute);
    builder.put(0x16f8cd7a6186e86dL, Category);
    builder.put(0x16f8cd7a6186e862L, Requirment);
    builder.put(0x16f8cd7a6186e86eL, Rule);
    builder.put(0x16f8cd7a61858813L, User);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
