package approvalworkflow.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptApproval = createDescriptorForApproval();
  /*package*/ final ConceptDescriptor myConceptAttribute = createDescriptorForAttribute();
  /*package*/ final ConceptDescriptor myConceptCategory = createDescriptorForCategory();
  /*package*/ final ConceptDescriptor myConceptRequirment = createDescriptorForRequirment();
  /*package*/ final ConceptDescriptor myConceptRule = createDescriptorForRule();
  /*package*/ final ConceptDescriptor myConceptUser = createDescriptorForUser();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptApproval, myConceptAttribute, myConceptCategory, myConceptRequirment, myConceptRule, myConceptUser);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Approval:
        return myConceptApproval;
      case LanguageConceptSwitch.Attribute:
        return myConceptAttribute;
      case LanguageConceptSwitch.Category:
        return myConceptCategory;
      case LanguageConceptSwitch.Requirment:
        return myConceptRequirment;
      case LanguageConceptSwitch.Rule:
        return myConceptRule;
      case LanguageConceptSwitch.User:
        return myConceptUser;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForApproval() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("approvalworkflow", "Approval", 0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L, 0x16f8cd7a6186e86fL);
    b.class_(false, false, false);
    b.origin("r:3daa3f1c-6e0a-4040-af8a-c360298e1d4c(approvalworkflow.structure)/1655298788564592751");
    b.version(2);
    b.property("type", 0x16f8cd7a6186e8ceL).type(PrimitiveTypeId.STRING).origin("1655298788564592846").done();
    b.aggregate("requirement", 0x16f8cd7a6186e8c3L).target(0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L, 0x16f8cd7a6186e862L).optional(true).ordered(true).multiple(true).origin("1655298788564592835").done();
    b.aggregate("approvers", 0x16f8cd7a6186e8c5L).target(0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L, 0x16f8cd7a6186e86fL).optional(true).ordered(true).multiple(true).origin("1655298788564592837").done();
    b.aggregate("approvedby", 0x16f8cd7a6186e8d0L).target(0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L, 0x16f8cd7a6186e86fL).optional(true).ordered(true).multiple(true).origin("1655298788564592848").done();
    b.aggregate("rejectedby", 0x16f8cd7a6186e8d4L).target(0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L, 0x16f8cd7a6186e86fL).optional(true).ordered(true).multiple(true).origin("1655298788564592852").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAttribute() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("approvalworkflow", "Attribute", 0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L, 0x16f8cd7a6186e877L);
    b.class_(false, false, false);
    b.origin("r:3daa3f1c-6e0a-4040-af8a-c360298e1d4c(approvalworkflow.structure)/1655298788564592759");
    b.version(2);
    b.property("attributename", 0x16f8cd7a6186e878L).type(PrimitiveTypeId.STRING).origin("1655298788564592760").done();
    b.property("value", 0x16f8cd7a6186e87aL).type(PrimitiveTypeId.INTEGER).origin("1655298788564592762").done();
    b.property("unit", 0x16f8cd7a6186e881L).type(PrimitiveTypeId.STRING).origin("1655298788564592769").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCategory() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("approvalworkflow", "Category", 0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L, 0x16f8cd7a6186e86dL);
    b.class_(false, false, false);
    b.origin("r:3daa3f1c-6e0a-4040-af8a-c360298e1d4c(approvalworkflow.structure)/1655298788564592749");
    b.version(2);
    b.property("name", 0x16f8cd7a6186e870L).type(PrimitiveTypeId.STRING).origin("1655298788564592752").done();
    b.aggregate("attributes", 0x16f8cd7a6186e875L).target(0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L, 0x16f8cd7a6186e877L).optional(true).ordered(true).multiple(true).origin("1655298788564592757").done();
    b.aggregate("approvers", 0x16f8cd7a6186e88aL).target(0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L, 0x16f8cd7a61858813L).optional(true).ordered(true).multiple(true).origin("1655298788564592778").done();
    b.aggregate("rules", 0x16f8cd7a6186e88dL).target(0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L, 0x16f8cd7a6186e86eL).optional(true).ordered(true).multiple(true).origin("1655298788564592781").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRequirment() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("approvalworkflow", "Requirment", 0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L, 0x16f8cd7a6186e862L);
    b.class_(false, false, false);
    b.origin("r:3daa3f1c-6e0a-4040-af8a-c360298e1d4c(approvalworkflow.structure)/1655298788564592738");
    b.version(2);
    b.property("name", 0x16f8cd7a6186e863L).type(PrimitiveTypeId.STRING).origin("1655298788564592739").done();
    b.aggregate("requiror", 0x16f8cd7a6186e868L).target(0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L, 0x16f8cd7a61858813L).optional(false).ordered(true).multiple(false).origin("1655298788564592744").done();
    b.aggregate("category", 0x16f8cd7a6186e86aL).target(0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L, 0x16f8cd7a6186e86dL).optional(true).ordered(true).multiple(true).origin("1655298788564592746").done();
    b.aggregate("attributes", 0x16f8cd7a6186e892L).target(0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L, 0x16f8cd7a6186e877L).optional(true).ordered(true).multiple(true).origin("1655298788564592786").done();
    b.aggregate("supplier", 0x16f8cd7a6186e896L).target(0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L, 0x16f8cd7a61858813L).optional(false).ordered(true).multiple(false).origin("1655298788564592790").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRule() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("approvalworkflow", "Rule", 0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L, 0x16f8cd7a6186e86eL);
    b.class_(false, false, false);
    b.origin("r:3daa3f1c-6e0a-4040-af8a-c360298e1d4c(approvalworkflow.structure)/1655298788564592750");
    b.version(2);
    b.property("name", 0x16f8cd7a6186e8a5L).type(PrimitiveTypeId.STRING).origin("1655298788564592805").done();
    b.property("type", 0x16f8cd7a6186e8bcL).type(PrimitiveTypeId.STRING).origin("1655298788564592828").done();
    b.property("criteria", 0x16f8cd7a6186e8bfL).type(PrimitiveTypeId.STRING).origin("1655298788564592831").done();
    b.aggregate("category", 0x16f8cd7a6186e8b1L).target(0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L, 0x16f8cd7a6186e86dL).optional(false).ordered(true).multiple(false).origin("1655298788564592817").done();
    b.aggregate("approvers", 0x16f8cd7a6186e8b3L).target(0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L, 0x16f8cd7a61858813L).optional(true).ordered(true).multiple(true).origin("1655298788564592819").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUser() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("approvalworkflow", "User", 0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L, 0x16f8cd7a61858813L);
    b.class_(false, false, false);
    b.origin("r:3daa3f1c-6e0a-4040-af8a-c360298e1d4c(approvalworkflow.structure)/1655298788564502547");
    b.version(2);
    b.property("name", 0x16f8cd7a6186e84fL).type(PrimitiveTypeId.STRING).origin("1655298788564592719").done();
    b.property("hierarchy", 0x16f8cd7a6186e852L).type(PrimitiveTypeId.INTEGER).origin("1655298788564592722").done();
    b.aggregate("superior", 0x16f8cd7a6186e85eL).target(0xf4c726b18a9f431cL, 0xa55ad6c1445e5f46L, 0x16f8cd7a61858813L).optional(true).ordered(true).multiple(true).origin("1655298788564592734").done();
    return b.create();
  }
}
